//! Every primitive, replayed against bytes Lucene's own writers produced.
//!
//! The fixture is `fixtures/lucene-4-7-primitive-vectors.tsv`, generated by
//! the judge's `CodecVectors` class inside the pinned Sling image. Its
//! header records the command.
//!
//! These encodings are small enough that a self-consistent mistake survives
//! a round trip: a variable-length integer written big-endian reads back
//! through froe's own reader, a packed block padded to eight bytes parses,
//! and a monotonic block whose average is computed in double reconstructs
//! almost every value. Only Lucene's own bytes catch those, which is why
//! this file compares against a fixture rather than against froe.

use std::path::Path;

use froe::index::lucene::codec::data_output::CodecOutput;
use froe::index::lucene::codec::packed;

/// One case from the fixture.
struct Vector {
    primitive: String,
    input: String,
    expected: Vec<u8>,
}

/// Every case, in file order.
fn vectors() -> Vec<Vector> {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/lucene-4-7-primitive-vectors.tsv");
    let content = std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("read {}: {error}", path.display()));
    let cases: Vec<Vector> = content
        .lines()
        .filter(|line| !line.starts_with('#') && !line.trim().is_empty())
        .map(|line| {
            let mut fields = line.splitn(3, '\t');
            let primitive = fields.next().expect("a primitive").to_owned();
            let input = fields.next().expect("an input").to_owned();
            let hex = fields.next().expect("expected bytes");
            Vector {
                primitive,
                input,
                expected: decode_hex(hex),
            }
        })
        .collect();
    assert!(
        cases.len() > 100,
        "the fixture holds {} cases, which is fewer than it was generated with",
        cases.len()
    );
    cases
}

fn decode_hex(hex: &str) -> Vec<u8> {
    assert!(hex.len().is_multiple_of(2), "an odd hex string: {hex:?}");
    (0..hex.len())
        .step_by(2)
        .map(|at| u8::from_str_radix(&hex[at..at + 2], 16).expect("hex"))
        .collect()
}

/// Runs `write` into a fresh buffer and returns what it wrote.
fn written(write: impl FnOnce(&mut CodecOutput<&mut Vec<u8>>)) -> Vec<u8> {
    let mut buffer = Vec::new();
    {
        let mut output = CodecOutput::new(&mut buffer);
        write(&mut output);
        assert_eq!(
            output.position() as usize,
            buffer.len(),
            "the position counter disagrees with what reached the sink"
        );
    }
    buffer
}

/// Compares, naming the case and the first differing byte.
fn assert_bytes(case: &Vector, produced: &[u8]) {
    if produced == case.expected {
        return;
    }
    let first = produced
        .iter()
        .zip(case.expected.iter())
        .position(|(ours, theirs)| ours != theirs);
    panic!(
        "{} {:?}: froe wrote {} bytes, Lucene wrote {}{}",
        case.primitive,
        case.input,
        produced.len(),
        case.expected.len(),
        match first {
            Some(at) => format!(
                "; first difference at byte {at}: {:#04x} against {:#04x}",
                produced[at], case.expected[at]
            ),
            None => String::new(),
        }
    );
}

#[test]
fn every_primitive_vector_is_reproduced_byte_for_byte() {
    let mut seen = std::collections::BTreeSet::new();
    for case in vectors() {
        seen.insert(case.primitive.split(':').next().unwrap_or("").to_owned());
        let produced = match case.primitive.as_str() {
            "vint" => {
                let value: i32 = case.input.parse().expect("an int");
                written(|output| output.write_vint(value).expect("write"))
            }
            "vlong" => {
                let value: i64 = case.input.parse().expect("a long");
                written(|output| output.write_vlong(value).expect("write"))
            }
            "int" => {
                let value: i32 = case.input.parse().expect("an int");
                written(|output| output.write_int(value).expect("write"))
            }
            "long" => {
                let value: i64 = case.input.parse().expect("a long");
                written(|output| output.write_long(value).expect("write"))
            }
            "string" => {
                let value = unescape(&case.input);
                written(|output| output.write_string(&value).expect("write"))
            }
            "stringmap" => {
                let entries = parse_map(&case.input);
                let borrowed: Vec<(&str, &str)> = entries
                    .iter()
                    .map(|(key, value)| (key.as_str(), value.as_str()))
                    .collect();
                written(|output| output.write_string_map(borrowed).expect("write"))
            }
            "stringset" => {
                let values = parse_set(&case.input);
                let borrowed: Vec<&str> = values.iter().map(String::as_str).collect();
                written(|output| output.write_string_set(borrowed).expect("write"))
            }
            "blockpacked" => {
                let values = parse_longs(&case.input);
                written(|output| {
                    packed::write_block_packed(output, &values).expect("write");
                })
            }
            "monotonic" => {
                let values = parse_longs(&case.input);
                written(|output| {
                    packed::write_monotonic_block_packed(output, &values).expect("write");
                })
            }
            other if other.starts_with("packed:") => {
                let bits: u32 = other
                    .strip_prefix("packed:")
                    .expect("the prefix")
                    .parse()
                    .expect("a width");
                let values: Vec<u64> = case
                    .input
                    .split(',')
                    .map(|value| value.parse::<u64>().expect("an unsigned value"))
                    .collect();
                written(|output| {
                    packed::write_packed(output, &values, bits).expect("write");
                })
            }
            other => panic!("the fixture holds a primitive this test does not drive: {other}"),
        };
        assert_bytes(&case, &produced);
    }

    // The fixture is the specification's own witness, so a primitive missing
    // from it is a gap in the evidence rather than a passing test.
    for expected in [
        "vint",
        "vlong",
        "int",
        "long",
        "string",
        "stringmap",
        "stringset",
        "packed",
        "blockpacked",
        "monotonic",
    ] {
        assert!(
            seen.contains(expected),
            "the fixture carries no {expected} case; seen {seen:?}"
        );
    }
}

/// The `\uXXXX` escaping `CodecVectors.escape` applies, undone.
fn unescape(input: &str) -> String {
    let mut out = String::new();
    let mut characters = input.chars();
    let mut units: Vec<u16> = Vec::new();
    while let Some(character) = characters.next() {
        if character != '\\' {
            if !units.is_empty() {
                out.push_str(&String::from_utf16_lossy(&units));
                units.clear();
            }
            out.push(character);
            continue;
        }
        assert_eq!(characters.next(), Some('u'), "only \\u escapes are written");
        let digits: String = characters.by_ref().take(4).collect();
        units.push(u16::from_str_radix(&digits, 16).expect("a code unit"));
    }
    if !units.is_empty() {
        out.push_str(&String::from_utf16_lossy(&units));
    }
    out
}

/// `{one=1,two=2}` as pairs, in file order.
fn parse_map(input: &str) -> Vec<(String, String)> {
    let inner = input.trim_start_matches('{').trim_end_matches('}');
    if inner.is_empty() {
        return Vec::new();
    }
    inner
        .split(',')
        .map(|entry| {
            let (key, value) = entry.split_once('=').expect("a key=value pair");
            (key.to_owned(), value.to_owned())
        })
        .collect()
}

/// `[a,b]` as values, in file order.
fn parse_set(input: &str) -> Vec<String> {
    let inner = input.trim_start_matches('[').trim_end_matches(']');
    if inner.is_empty() {
        return Vec::new();
    }
    inner.split(',').map(str::to_owned).collect()
}

fn parse_longs(input: &str) -> Vec<i64> {
    input
        .split(',')
        .map(|value| value.parse::<i64>().expect("a long"))
        .collect()
}
