//! `\p{Nd}` of Unicode 6.3.0: the decimal digits.
//!
//! The one general category the grammar names, intersected with the
//! half- and full-width block in the `Numeric` macro. The database
//! gives one line per code point, with a `First`/`Last` pair for a
//! range, so the generator folds it back into ranges.
//!
//! Generated by `cargo run --example generate_unicode_tables`
//! from `UnicodeData.txt`, sha256 `3f76924f0410ca8ae0e9b5c59bd1ba03196293c32616204b393300f091f52013`.
//!
//! This file's own sha256, over every line below this header:
//! `4996dc18a67c6b83aebc42db902644729fa989b5d5375c89c8b5fe8cb42f3e59`.

/// The ranges, ascending, non-overlapping, and total over the code
/// point space by way of the default every uncovered point takes.
#[rustfmt::skip]
pub(crate) const TABLE: &[(u32, u32, bool)] = &[
    (0x00030,0x00039,true), (0x00660,0x00669,true), (0x006f0,0x006f9,true), (0x007c0,0x007c9,true), 
    (0x00966,0x0096f,true), (0x009e6,0x009ef,true), (0x00a66,0x00a6f,true), (0x00ae6,0x00aef,true), 
    (0x00b66,0x00b6f,true), (0x00be6,0x00bef,true), (0x00c66,0x00c6f,true), (0x00ce6,0x00cef,true), 
    (0x00d66,0x00d6f,true), (0x00e50,0x00e59,true), (0x00ed0,0x00ed9,true), (0x00f20,0x00f29,true), 
    (0x01040,0x01049,true), (0x01090,0x01099,true), (0x017e0,0x017e9,true), (0x01810,0x01819,true), 
    (0x01946,0x0194f,true), (0x019d0,0x019d9,true), (0x01a80,0x01a89,true), (0x01a90,0x01a99,true), 
    (0x01b50,0x01b59,true), (0x01bb0,0x01bb9,true), (0x01c40,0x01c49,true), (0x01c50,0x01c59,true), 
    (0x0a620,0x0a629,true), (0x0a8d0,0x0a8d9,true), (0x0a900,0x0a909,true), (0x0a9d0,0x0a9d9,true), 
    (0x0aa50,0x0aa59,true), (0x0abf0,0x0abf9,true), (0x0ff10,0x0ff19,true), (0x104a0,0x104a9,true), 
    (0x11066,0x1106f,true), (0x110f0,0x110f9,true), (0x11136,0x1113f,true), (0x111d0,0x111d9,true), 
    (0x116c0,0x116c9,true), (0x1d7ce,0x1d7ff,true), 
];
